### PR TITLE
clm slopes: fixing and renaming key

### PR DESCRIPTION
**Pull request by jswilley-csm**
We have fixed an issue with the slope aspect key in CLM, Solver.CLM.UseSlopeAspect, formerly Solver.SlopeAccountingCLM. 

There was a problem with an internal value for pi and a variable name in Fortran as well as an issue where the key was not correctly turning off slope accounting. 

We changed the name of the key to better fit the established naming convention.

### CODE REVIEW

**Comment by smithsg84** [comment]
This commit is showing conflicts that must be resolved.   I believe the latest set of changes were applied on top of your previous branch and a PR was submitted based on that branch a second time.   This creates a problem since your branch will be out-of-date with master since we merged your previous PR as a swash merge.

**Comment by jswilley-csm** [comment]
I went ahead and resolved the merge conflicts that we were seeing. It looks like all of them were disagreements between my previous commit and latest commit. It didn't look like the author of the most recent commit changed any of the same lines that we did, which is convenient.

This was my first merge conflict resolution, so let me know if you find any mistakes. I will be happy to go back to the drawing board if need be.

**Review by smithsg84 — APPROVED** [review]
Thanks for patches.

**Comment by smithsg84** [comment]
Checks are passing in Travis but passing status is not getting reflected on GitHub.   Will merge.

**Pull request merged**
