### PR TITLE
Fix CLM initialization bug (performance issue)

### PR DESCRIPTION
**Pull request by hokkanen**
Fixes a performance issue with CLM initialization. Reduced the CLM initialization time for a production case from >5 hours to <10 seconds.

### CODE REVIEW

**Review by smithsg84 — DISMISSED** [review]

**Comment by reedmaxwell** [comment]
Steve, we are seeing different behavior with this fix in big runs than without it.  I think we need more testing before the PR is accepted

Reed

Reed M. Maxwell, Ph.D.
Research Professor
Colorado School of Mines
Director, Integrated GroundWater Modeling Center
Professor, Princeton University
maxwell.princeton.edu<http://maxwell.princeton.edu>


On Sep 22, 2020, at 3:00 PM, Steven Smith <notifications@github.com<mailto:notifications@github.com>> wrote:



@smithsg84 approved this pull request.

**Comment by smithsg84** [comment]
OK, is this exposing some kind of other error?

The kpatch setting looks really wrong in the original and the z/zi initialization looks like it needs the initialization.

**Comment by skollet** [comment]
When Jaro and I discussed this, we concluded that the fix does not change the results, because at k, z and zi are the same for all t. 
Of course this requires that l = 1+i + j_incr*(j) + k_incr*(clm(t)%topo_mask(1)-(k-1)) is correct.

**Comment by reedmaxwell** [comment]
Hi Stefan-

I think you are correct looking through the logic.  I’ll dive in more deeply.  thanks

Reed

Reed M. Maxwell, Ph.D.
Research Professor
Colorado School of Mines
Director, Integrated GroundWater Modeling Center
Professor, Princeton University
maxwell.princeton.edu<http://maxwell.princeton.edu>


On Sep 23, 2020, at 10:13 AM, skollet <notifications@github.com<mailto:notifications@github.com>> wrote:



When Jaro and I discussed this, we concluded that the fix does not change the results, because at k, z and zi are the same for all t.
Of course this requires that l = 1+i + j_incr*(j) + k_incr*(clm(t)%topo_mask(1)-(k-1)) is correct.

**Comment by smithsg84** [comment]
@reedmaxwell There was an email about this patch causing a problem.   Is this CLM fix OK to merge?
Thanks,
Steve

**Comment by reedmaxwell** [comment]
@Hoang, did you finalize testing of this?

Reed M. Maxwell, Ph.D.
Research Professor
Colorado School of Mines
Director, Integrated GroundWater Modeling Center
Professor, Princeton University
maxwell.princeton.edu<http://maxwell.princeton.edu>


On Oct 14, 2020, at 10:27 AM, Steven Smith <notifications@github.com<mailto:notifications@github.com>> wrote:



@reedmaxwell<https://github.com/reedmaxwell> There was an email about this patch causing a problem. Is this CLM fix OK to merge?
Thanks,
Steve

**Comment by reedmaxwell** [comment]
Hi Reed,

Is this the pull request from Jaro? Yes I finalized testing it in the UCRB. The result is exactly the same as one from the current version of ParFlow.

Thanks,
Hoang

Hoang Tran, Ph.D.
Postdoctoral Scholar
Department of Civil and Environmental Engineering
Princeton University


From: Reed Maxwell <rmaxwell@mines.edu>
Date: Wednesday, October 14, 2020 at 11:09 AM
To: parflow/parflow <reply@reply.github.com>
Cc: parflow/parflow <parflow@noreply.github.com>, Mention <mention@noreply.github.com>, "Condon, Laura - (lecondon)" <lecondon@arizona.edu>, Hoang Viet Tran <hoangtran@princeton.edu>
Subject: Re: [External] Re: [parflow/parflow] Fix CLM initialization bug (performance issue) (#272)

@Hoang, did you finalize testing of this?

Reed M. Maxwell, Ph.D.
Research Professor
Colorado School of Mines
Director, Integrated GroundWater Modeling Center
Professor, Princeton University
maxwell.princeton.edu<http://maxwell.princeton.edu>


On Oct 14, 2020, at 10:27 AM, Steven Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@reedmaxwell<https://github.com/reedmaxwell> There was an email about this patch causing a problem. Is this CLM fix OK to merge?
Thanks,
Steve

**Comment by reedmaxwell** [comment]
thanks Hoang, we are good to go on the PR

Reed M. Maxwell, Ph.D.
Research Professor
Colorado School of Mines
Director, Integrated GroundWater Modeling Center
Professor, Princeton University
maxwell.princeton.edu<http://maxwell.princeton.edu>


On Oct 14, 2020, at 11:24 AM, Hoang Viet Tran <hoangtran@princeton.edu<mailto:hoangtran@princeton.edu>> wrote:

Hi Reed,

Is this the pull request from Jaro? Yes I finalized testing it in the UCRB. The result is exactly the same as one from the current version of ParFlow.

Thanks,
Hoang

Hoang Tran, Ph.D.
Postdoctoral Scholar
Department of Civil and Environmental Engineering
Princeton University


From: Reed Maxwell <rmaxwell@mines.edu<mailto:rmaxwell@mines.edu>>
Date: Wednesday, October 14, 2020 at 11:09 AM
To: parflow/parflow <reply@reply.github.com<mailto:reply@reply.github.com>>
Cc: parflow/parflow <parflow@noreply.github.com<mailto:parflow@noreply.github.com>>, Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>, "Condon, Laura - (lecondon)" <lecondon@arizona.edu<mailto:lecondon@arizona.edu>>, Hoang Viet Tran <hoangtran@princeton.edu<mailto:hoangtran@princeton.edu>>
Subject: Re: [External] Re: [parflow/parflow] Fix CLM initialization bug (performance issue) (#272)

@Hoang, did you finalize testing of this?

Reed M. Maxwell, Ph.D.
Research Professor
Colorado School of Mines
Director, Integrated GroundWater Modeling Center
Professor, Princeton University
maxwell.princeton.edu<http://maxwell.princeton.edu/>


On Oct 14, 2020, at 10:27 AM, Steven Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


@reedmaxwell<https://github.com/reedmaxwell> There was an email about this patch causing a problem. Is this CLM fix OK to merge?
Thanks,
Steve

**Comment by smithsg84** [comment]
Thanks,
Steve

________________________________

**Review by smithsg84 — APPROVED** [review]

**Pull request merged**
