### PR TITLE
Pf-keys: Constrain lists of names + bugfix

### PR DESCRIPTION
**Pull request by DrewLazzeriKitware**
### 3) Add [constraint](https://github.com/parflow/parflow/pull/352/commits/9b079991003cdb7fa92f8e36d97166f9255af462) for lists of names

This change lets us express that one list of names should be a subset of another list of names

### Constraint Example

Values for `PhaseSources.{phase_name}.GeomNames` should be a subset of values from either `GeomInput.{geom_input_name}.GeomNames` or `GeomInput.{geom_input_name}.GeomName`. Setting the domain to `EnumDomain` [like so](https://github.com/parflow/parflow/pull/352/commits/9b079991003cdb7fa92f8e36d97166f9255af462#diff-b748c613739cd14a137bd5d77f23421c7388e51f525ce3dfc1d31f3e3c48e25eR517-R520) expresses that constraint. A more detailed example can be seen [in this test case](https://github.com/parflow/parflow/pull/352/commits/9b079991003cdb7fa92f8e36d97166f9255af462#diff-281017c9aee6be609d277a565070cc7b07bf2789c10d5feaea462346024e7710R230-R233).

### CODE REVIEW

**Comment by smithsg84** [comment]
Is this ready for review?   Please mark issues that are not ready with DRAFT: or WIP:

**Comment by DrewLazzeriKitware** [comment]
Marked wip, thanks.

**Comment by DrewLazzeriKitware** [comment]
@smithsg84 @jourdain This is now ready for review.

**Comment by jourdain** [comment]
LGTM, should be ready for review now.

**Review by smithsg84 — DISMISSED** [review]

**Comment by smithsg84** [comment]
Several python tests are failing,  is this passing in your local env?

https://github.com/parflow/parflow/pull/352/checks?check_run_id=3293124657

**Comment by DrewLazzeriKitware** [comment]
I'm looking into these tests which are failing locally on this branch, but not on master: 

- [ ] py_clm_file_handling
- [ ] py_from_definition
- [ ] py_pfidb_pfset
- [ ] py_pfset_test
- [ ] py_selection_methods

**Comment by jourdain** [comment]
@DrewLazzeriKitware are the test working locally now?

**Comment by DrewLazzeriKitware** [comment]
> @DrewLazzeriKitware are the tests working locally now?

With the change two more are passing. I'm still looking at the remaining three.

**Comment by DrewLazzeriKitware** [comment]
There are three tests still failing on my machine, but I found that the same tests are failing in the master branch on my machine: 
```
py_default_single_3_3_3
py_default_richards_3_3_3
py_simple-mask
```

@smithsg84 Could we trigger the CI again to see if these clear up?

**Comment by DrewLazzeriKitware** [comment]
I've forced pushed to remove some auto-formatting that made diffs unreadable - the tests pass on the unformatted and pushed version though.

**Comment by smithsg84** [comment]
The 3_3_3 tests is running a 27 rank tests, that could be failing if your MPI prohibits oversubscribing cores, frequently you can pass extra flags to MPI to enable this (-oversubscribe for OpenMPI)   The FindMPI in CMAKE can set extra MPI flags.

https://cmake.org/cmake/help/latest/module/FindMPI.html

The oversubscribing doesn't run to poorly for simple tests.   You may also need to turn off busy waiting:

https://github.com/parflow/parflow/wiki/ParFlow-FAQ#how-to-run-parflow-tests-with-a-small-number-of-cores

Not sure why the other test would be failing.

**Review by smithsg84 — APPROVED** [review]

**Pull request merged**
