### PR TITLE
Indent solver_richards.c for easier merging

### PR DESCRIPTION
**Pull request by smithsg84**

### CODE REVIEW

**Comment by xy124** [comment]
Can you tell me please which Indenter you are finally using (with which options?)
I'd like to indent my version of solver_richards.c too so the merge is easier ;)

**Comment by kulkarni1** [comment]
I think Steve is using uncrustify package for this.

**Comment by smithsg84** [comment]
I will be pushing config and files today

**Comment by smithsg84** [comment]
The master branch has been reformatted.  There is a short script to reformat all the code 

parflow/bin/pfformat

Assumes uncrustify is installed.  The uncrustify configure file is bin/parflow.cfg.   

Steve

**Pull request merged**
