### PR TITLE
print_van_Genuchten

### PR DESCRIPTION
**Pull request by ben-bou**
Stores the van Genuchten parameters `alpha`, `n`, `sres`, `ssat` in `problem_data`
and prints them in `solver_richards.c` if `print_subsurf_data` is set. Memory usage is increased by these four vectors which  store one value for every gridpoint. Performance should not be affected because the values are generated anyway.

### CODE REVIEW

**Comment by reedmaxwell** [comment]
> Stores the van Genuchten parameters `alpha`, `n`, `sres`, `ssat` in `problem_data`
> and prints them in `solver_richards.c` if `print_subsurf_data` is set. Memory usage is increased by these four vectors which store one value for every gridpoint. Performance should not be affected because the values are generated anyway.

this is a nice feature, we should get this PR through.  Is it ready to go?

**Comment by smithsg84** [comment]
Branch has conflicts that have to be resolved.

**Comment by reedmaxwell** [comment]
> Branch has conflicts that have to be resolved.

thanks, yes, that should have been obvious : )

@ben-bou this is a great feature add, it would be nice to have the conflicts resolved and get this pushed

**Comment by smithsg84** [comment]
Not sure what is going on with the changes, there are a lot of differences in file not related to this patch.

**Comment by ben-bou** [comment]
> Not sure what is going on with the changes, there are a lot of differences in file not related to this patch.

@smithsg84 I believe the file changes are there because I branched of @hokkanen 's CUDA11 branch. None of the conflicting files are actually relevant for this PR. How do we proceed with this?

**Comment by smithsg84** [comment]
The PR needs to have the non-related changes removed.

**Comment by smithsg84** [comment]
Why is the reading of the new vectors necessary?   It looks to me like the pd_alphas/N/sres/ssat arrays are being computed in the problem_saturation.c loop after the VGInit method is called so the read values will be overwritten.

This is going to impact performance more than suggested.   Yes the values are calculated but this is dramatically increasing the memory writes in the loop.   Going from 1 write to 5.    Memory movement is more important than FLOPS these days.

**Comment by smithsg84** [comment]
I have reworked this feature to avoid keeping the values in problem data and reassigning the vectors each time saturation is invoked.

**Comment by smithsg84** [comment]
The feature in the branch was reworked by extending the PFModule API to include methods for outputing module state.   This saves reating new problem data state and the vector assignments are only done when the output is needed.

The van Genuchten printing was merge in #336 

Thanks for submitting the code it was helpful to base things on even if we didn't use it directly.

**Pull request closed without merging**
