### PR TITLE
Bugfix dirichlet

### PR DESCRIPTION
**Pull request by reedmaxwell**
@skollet thanks for making this change / fix to the lower BC!  I think this is good to go, right?  (other than the fact that it looks like GitHub has attributed the wrong user for the fix)

@smithsg84 @lecondon do you agree that this is all set?

### CODE REVIEW

**Comment by lecondon** [comment]
@reedmaxwell @skollet, yes I agree, I think this is good to go. I can provide an official review if needed.

**Comment by smithsg84** [comment]
@lecondon Approving reviews as you look at things helps so can easily see who has looked at changes.

This is showing changes in a couple of the regressions tests.   Do the regression test files simply need updating, these have Dirichlet on bottom so would be expected to change with the patch.  test_XPlusYPlusZ and test_XYZTPlus1 are in the examples directory.

The following tests FAILED:
	180 - pfclm_sc.tcl (Failed)
Errors while running CTest
	181 - pfclm_sc.tcl_1_2_1 (Failed)
	182 - pfclm_sc.tcl_2_1_1 (Failed)
	183 - pfclm_sc.tcl_2_2_1 (Failed)
	184 - pfclm_sc.tcl_3_3_1 (Failed)
	185 - pfclm_sc.tcl_1_4_1 (Failed)
	186 - pfclm_sc.tcl_4_1_1 (Failed)
	199 - test_XPlusYPlusZ.tcl (Failed)
	201 - test_XYZTPlus1.tcl (Failed)

**Review by lecondon — APPROVED** [review]
I don't have any additional chances to suggest

**Comment by skollet** [comment]
@Steve Yes, you are right I should fix these test data sets before opening a pull request. Hope I am able to do it soon.

**Comment by skollet** [comment]
Thanks Steve for pointing that out. I hope to get to it soon...

**Pull request closed without merging**
