### PR TITLE
Compatibility Refactoring for Kokkos starting from v4.0 and a bug Fix for Kokkos (HIP) execution space

### PR DESCRIPTION
**Pull request by mfahdaz**
This PR refactors deprecated code in for compatibility with Kokkos starting from version v4.0, and resolves a bug related to multiple finalize calls in the Kokkos HIP execution space.

However, further refactoring is required for the Kokkos backend code to remove deprecated code in Kokkos v3.x. Meanwhile, the following CMake configuration can be used to enable support for deprecated code when compiling Kokkos:

`-DKokkos_ENABLE_DEPRECATED_CODE_3=ON`

I have thoroughly tested these changes with various run configurations and variants of the testcase [clayL.tcl](https://github.com/parflow/parflow/blob/master/test/tcl/clayL.tcl) on
- [JURECA (AMD MI250 GPUs)](https://apps.fz-juelich.de/jsc/hps/jureca/evaluation-platform-overview.html), and
- [LUMI (AMD MI250X GPUs based on the 2nd Gen AMD CDNA architecture)](https://docs.lumi-supercomputer.eu/hardware/lumig/).

Here are additional configuration details of the setup for the runs:

- Kokkos version: 4.2.0
- Parflow version: v3.12.0-26-g24ac8775

### CODE REVIEW

**Comment by smithsg84** [comment]
Thanks for the patch.  The existing Kokkos test build is failing.   Likely the CI system will need to use a newer Kokkos.  Patch can't be merged until tests are passing.

**Comment by mfahdaz** [comment]
> Thanks for the patch. The existing Kokkos test build is failing. Likely the CI system will need to use a newer Kokkos. Patch can't be merged until tests are passing.

Thank you for your feedback. I completely agree. The failure of the [CI Test Ubuntu 22.04 Kokkos Build](https://github.com/parflow/parflow/actions/runs/7836197110/job/21383275608?pr=508#step:20:266) is indeed due to the usage of an outdated version of Kokkos, resulting in the absence of the necessary scope guard `is_finalized()`.

After reviewing the [workflow file L197](https://github.com/parflow/parflow/actions/runs/7836197110/workflow?pr=508#L197), it became apparent that it fetches and installs an older version of Kokkos (v3.3.01). However, the necessary scope guard `is_finalized()` is only [available from version v3.7.00](https://github.com/kokkos/kokkos/blob/master/CHANGELOG.md#features-3) onward.

Considering that the current PR aims to enable Parflow to leverage the latest features and optimizations available in the most recent version of Kokkos (starting from version v4.x), I would suggest updating the workflow file to download and install the [latest version of Kokkos](https://github.com/kokkos/kokkos/releases/tag/4.2.00).

**Comment by smithsg84** [comment]
Getting error compile error after updating to Kokkos 4.2.0

/home/runner/work/parflow/parflow/pfsimulator/amps/mpi1/amps_gpupacking.cpp(358): error: namespace "Kokkos" has no member "InitArguments"

**Comment by mfahdaz** [comment]
The following CMAKE settings are necessary on [workflow file L203](https://github.com/parflow/parflow/actions/runs/7836197110/workflow?pr=508#L203) until the Kokkos backend undergoes complete refactoring:

`-DKokkos_ENABLE_DEPRECATED_CODE_3=ON`

**Comment by mfahdaz** [comment]
- Removed all deprecated code from the Kokkos backend, eliminating the need for cmake configuration settings to enable support for deprecated Kokkos code
- Upgraded the Kokkos dependency in the  [workflow](https://github.com/parflow/parflow/actions/runs/7836197110/workflow?pr=508#L203) to [version 4.2.1](https://github.com/kokkos/kokkos/releases/tag/4.2.01), ensuring compatibility with the latest enhancements and bug fixes.

The CI system should now pass successfully. This has been [tested](https://github.com/mfahdaz/parflow/actions/runs/8112409455) on my forked repository.

**Review by smithsg84 — APPROVED** [review]

**Pull request merged**
