### PR TITLE
Update silo url

### PR DESCRIPTION
**Pull request by psavery**
I didn't find any official documentation that the url changed. But you will
notice that these urls no longer work:

https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2.tar.gz
https://wci.llnl.gov/content/assets/docs/simulation/computer-codes/silo/silo-4.10.2/silo-4.10.2-bsd.tar.gz

And if you go to their [downloads page](https://wci.llnl.gov/simulation/computer-codes/silo), you will
see that the download links now point to these urls:

https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.10.2.tgz
https://wci.llnl.gov/sites/wci/files/2021-01/silo-4.10.2-bsd.tgz

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM

FYI @smithsg84

**Review by smithsg84 — APPROVED** [review]
Thanks for patch

**Comment by smithsg84** [comment]
The last release and master branch are using  GitHub to download Silo, as in the linux.yaml file:

 URL=https://github.com/LLNL/Silo/archive/refs/tags/4.11.tar.gz
 
I think GitHub should be less subject to changes.

**Comment by EnlNovius** [comment]
Yes, that's what I saw afterwards. The main Dockerfile no longer uses this link at all and uses the git, however the file [parflow/docker/dev/Dockerfile](https://github.com/parflow/parflow/blob/master/docker/dev/Dockerfile) has not been updated and continues to use this link.

**Pull request merged**
