### PR TITLE
Uncrustify

### PR DESCRIPTION
**Pull request by smithsg84**

### CODE REVIEW

**Comment by fonseca-ins** [comment]
Dear Steve:

Currently I cannot reproduce the exact indentation results in master with the uncrustify on my machine.  This makes the integration with the adaptive branch quite impossible.
Could you please share/document which version of uncrustify was used to format
the code ?

Best \ Jose

**Comment by fonseca-ins** [comment]
Hi Steve, 

I previously used version 0.66 and ran ./bin/pfformat on top 
of the master branch and that changed some files. Repeating the exercise with version 0.65  files
are not changed as expected.  Hence, I try to reformat adaptive with v0.65 and then merge master
but for some reason the many comments are formated with additional spacing so the diffs are huge. 

adaptive is currently one commit behind master, so reformating from your side will be great. Many thanks !

Jose

**Comment by smithsg84** [comment]
I have pushed up a merged branch called 'adaptive-pfformat-merge'.   It
passes ParFlow tests but we don't have any for the adaptive tests.   You
should be able to merge changes from this branch onto adaptive if looks
ok.   I had to do a bit of manual conflict resolution so there is a
potential for some errors.

The reformat was a pain but in the long run it should help with making
merges go more smoothly.

Steve

**Comment by fonseca-ins** [comment]
Thank you very much Steve, I just merged it into adaptive and everything
runs as expected. 

Best regards \ Jose

**Pull request merged**
